[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[deploy]
startCommand = "/app/nikan-developer"
healthcheckPath = "/login"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[env]]
XUI_PORT = "{{ PORT }}"
