[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[deploy]
startCommand = "/app/nikan-developer"
healthcheckPath = "/login"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[env]]
NikanDeveloper_PORT = "{{ PORT }}"
NikanDeveloper_BIN_FOLDER = "/app/bin"
NikanDeveloper_DB_FOLDER = "/app/data"
NikanDeveloper_MAIN_FOLDER = "/app/data"
NikanDeveloper_ENABLE_FAIL2BAN = "false"
